"""Shared disposable-repository fixtures for lab architecture checks."""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parents[1] / "scripts"
IMPORTER_DIR = Path(__file__).resolve().parents[1] / "importers"
sys.path.insert(0, str(SCRIPT_DIR))
sys.path.insert(0, str(IMPORTER_DIR))

import catalog


class RepositoryCase(unittest.TestCase):
    """Run integration checks in a disposable miniature repository."""

    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.root = Path(self.temporary.name)
        (self.root / ".meta/catalog/schema").mkdir(parents=True)
        (self.root / "niches").mkdir()
        shutil.copyfile(catalog.LAB_SCHEMA_PATH, self.root / ".meta/catalog/schema/lab.schema.json")
        shutil.copyfile(catalog.SOURCE_SCHEMA_PATH, self.root / ".meta/catalog/schema/source.schema.json")
        self.originals = {
            name: getattr(catalog, name)
            for name in ("ROOT", "NICHES", "SCHEMA_DIR", "LAB_SCHEMA_PATH", "SOURCE_SCHEMA_PATH", "SOURCES_PATH", "LABS_PATH", "CATALOG_PATH")
        }
        catalog.ROOT = self.root
        catalog.NICHES = self.root / "niches"
        catalog.SCHEMA_DIR = self.root / ".meta/catalog/schema"
        catalog.LAB_SCHEMA_PATH = catalog.SCHEMA_DIR / "lab.schema.json"
        catalog.SOURCE_SCHEMA_PATH = catalog.SCHEMA_DIR / "source.schema.json"
        catalog.SOURCES_PATH = self.root / ".meta/catalog/sources.json"
        catalog.LABS_PATH = self.root / ".meta/catalog/labs.json"
        catalog.CATALOG_PATH = self.root / "CATALOG.md"
        self.sources = {
            "external-a": {"type": "external", "name": "Source A", "url": "https://example.com/a", "reuse": {"policy": "copy"}},
            "external-b": {"type": "external", "name": "Source B", "url": "https://example.com/b", "reuse": {"policy": "review"}},
            "link-only": {"type": "external", "name": "Link Only", "url": "https://example.com/link", "reuse": {"policy": "link-only"}},
            "cloudcertprep": {"type": "external", "name": "CloudCertPrep", "url": "https://github.com/nastaso/cloudcertprep", "reuse": {"policy": "copy", "license": "MIT"}},
            "created": {"type": "local", "name": "Created by me"},
            "generated": {"type": "local", "name": "Generated by me"},
        }
        catalog.SOURCES_PATH.write_text(json.dumps(self.sources, indent=2) + "\n")
        (self.root / ".gitignore").write_text("cache/\n")
        subprocess.run(["git", "init", "--quiet", str(self.root)], check=True)

    def tearDown(self) -> None:
        for name, value in self.originals.items():
            setattr(catalog, name, value)
        self.temporary.cleanup()

    def add_lab(
        self,
        relative: str,
        provider: str = "created",
        item_id: str | None = None,
        url: str | None = None,
        order_status: str = "not-started",
        kind: str = "exercise",
    ) -> Path:
        """Create a valid lab fixture with deterministic placeholder tracking."""
        lab_dir = self.root / relative
        lab_dir.mkdir(parents=True)
        (lab_dir / "README.md").write_text("# A source-linked problem\n")
        source: dict[str, str] = {"provider": provider}
        if item_id is not None:
            source["item_id"] = item_id
            source["url"] = url or "https://example.com/item"
        created = "2026-01-01"
        metadata = {
            "title": "A source-linked problem",
            "kind": kind,
            "status": order_status,
            "skills": ["systems"],
            "source": source,
            "dates": {"created": created, "started": None, "updated": created, "completed": None},
            "tracking": {"content_sha256": "0" * 64},
        }
        (lab_dir / "lab.json").write_text(json.dumps(metadata, indent=2) + "\n")
        return lab_dir
